[package]
name = "axum_tonic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.6"
tonic = "0.7.2"
tokio = { version = "1.0", features = ["full"] }
futures = "0.3.21"
prost = "0.10.4"
http-body = "0.4.4"
hyper = "0.14.19"