[package]
name = "axum_tonic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.6"
tonic = "0.7.2"
hyper = "0.14.19"
futures = "0.3.21"
tower = "0.4"

[build-dependencies]
tonic-build = "0.7.2"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
prost = "0.10.4"
http-body = "0.4.4"
tower-http = { version = "0.3", features = ["compression-gzip", "cors", "compression-br", "compression-deflate", "trace"] }
tracing-subscriber = "0.3.11"