[package]
name = "axum_tonic"
version = "0.2.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Use Tonic with Axum"
homepage = "https://github.com/jvdwrf/axum-tonic"
keywords = ["axum", "tonic", "interop", "grpc", "web"]
categories = ["web-programming"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.1"
tonic = "0.10.2"
hyper = "0.14.19"
futures = "0.3.21"
tower = "0.4"

[build-dependencies]
tonic-build = "0.10.2"

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
prost = "0.12.3"
http-body = "0.4.4"
tower-http = { version = "0.4.4", features = [
    "compression-gzip",
    "cors",
    "compression-br",
    "compression-deflate",
    "trace",
] }
tracing-subscriber = "0.3.11"
